import React from 'react';
import { Row, Col } from 'react-bootstrap';
import lincsImage from '../../assets/img/hms_lincs_logo.png';
import bocoupImage from '../../assets/img/bocoup.png';
import FeedbackMailto from '../../components/FeedbackMailto';
import './about.scss';

class About extends React.Component {

  /**
  * Render out JSX for About.
  * @return {ReactElement} JSX markup.
  */
  render() {
    /* This is not really a "page with sidebar", but we want to push the content
       over to line up with the nav menu as though there *were* a sidebar. */
    return (
      <div className='about page-with-sidebar'>
        <div className="page-main constrained-width-text">

          <h1>About</h1>

          <p>
            <div className="logo">
              <a href='http://lincs.hms.harvard.edu/'>
                <img src={lincsImage} />
              </a>
              <a href='https://bocoup.com/'>
                <img src={bocoupImage} />
              </a>
            </div>

            The HMS LINCS Breast Cancer Browser is an online tool developed by
            the <a href="http://lincs.hms.harvard.edu">Harvard Medical School
            (HMS) LINCS Center</a> and <a href="https://bocoup.com/">Bocoup </a>
            to provide public access to both published and unpublished datasets
            generated by the HMS LINCS Center to investigate breast cancer
            biology and drug response. It also provides facile access to other
            resources developed by the HMS LINCS Center, such as tools for the
            analysis of perturbagen dose-response datasets and data about drug
            chemistry and polypharmacology.
          </p>

          <p>The HMS LINCS Breast Cancer Browser is subject to continuous
          development and expansion with new datasets. We welcome your
          feedback and questions at <FeedbackMailto/>.</p>

          <h3>Using the HMS LINCS Breast Cancer Browser</h3>

          <h4>Terms of use</h4>

          <p>Please see the <a href="http://lincs.hms.harvard.edu/terms">HMS
          LINCS Terms of Use</a> regarding use and citation of the published
          and unpublished data presented here.</p>

          <h4>Batch effects and experimental variability</h4>

          <p>Not captured in the data visualizations in this HMS LINCS Breast
          Cancer Browser is information about the experimental procedures used
          and the batches of perturbagens and cell lines relevant to each of
          these individual datasets. Because experimental design and batch
          variability can be significant confounders in biomedical studies, we
          strongly encourage users of these data to investigate the extensive
          experimental and reagent metadata reported alongside the source data
          files for each of these datasets in the <a
          href="http://lincs.hms.harvard.edu/db/">HMS LINCS Database</a>. A
          link to the relevant source data in the HMS LINCS Database is
          provided on each dataset landing page in this browser.</p>

          <h3>Funding</h3>

          <p>The <a href="http://lincs.hms.harvard.edu/">HMS LINCS Center </a>
          is funded by NIH grant U54 HL127365 and is part of the NIH <a
          href="http://www.lincsproject.org/">Library of Integrated
          Network-based Cellular Signatures (LINCS) Program</a>.</p>

        </div>
      </div>
    );
  }
}

export default About;
