export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_ACTIVE_FILTERS = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_ACTIVE_FILTERS';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_VIEW_BY = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_VIEW_BY';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_HIGHLIGHT = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_HIGHLIGHT';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_COLOR_BY = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_COLOR_BY';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_SORT_BY = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_SORT_BY';

export function changeActiveFilters(activeFilters) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_ACTIVE_FILTERS,
    activeFilters
  };
}

export function changeViewBy(viewBy) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_VIEW_BY,
    viewBy
  };
}

export function changeHighlight(highlightId) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_HIGHLIGHT,
    highlightId
  };
}

export function changeGrowthFactorColorBy(growthFactorColorBy) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_COLOR_BY,
    growthFactorColorBy
  };
}

export function changeGrowthFactorSortBy(growthFactorSortBy) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_SORT_BY,
    growthFactorSortBy
  };
}
