export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_ACTIVE_FILTERS = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_ACTIVE_FILTERS';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_VIEW_BY = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_VIEW_BY';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_HIGHLIGHTED_CELL_LINE = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_HIGHLIGHTED_CELL_LINE';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_TOGGLED_CELL_LINE = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_TOGGLED_CELL_LINE';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_COLOR_BY = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_COLOR_BY';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_SORT_BY = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_SORT_BY';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_HIGHLIGHTED_GROWTH_FACTOR = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_HIGHLIGHTED_GROWTH_FACTOR';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_TOGGLED_GROWTH_FACTOR = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_TOGGLED_GROWTH_FACTOR';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_CELL_LINE_COLOR_BY = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_CELL_LINE_COLOR_BY';
export const DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_CELL_LINE_SORT_BY = 'DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_CELL_LINE_SORT_BY';

export function changeActiveFilters(activeFilters) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_ACTIVE_FILTERS,
    activeFilters
  };
}

export function changeViewBy(viewBy) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_VIEW_BY,
    viewBy
  };
}

export function changeHighlightedCellLine(highlightId) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_HIGHLIGHTED_CELL_LINE,
    highlightId
  };
}

export function changeToggledCellLine(toggledId) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_TOGGLED_CELL_LINE,
    toggledId
  };
}


export function changeGrowthFactorColorBy(growthFactorColorBy) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_COLOR_BY,
    growthFactorColorBy
  };
}

export function changeGrowthFactorSortBy(growthFactorSortBy) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_GROWTH_FACTOR_SORT_BY,
    growthFactorSortBy
  };
}


export function changeHighlightedGrowthFactor(highlightId) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_HIGHLIGHTED_GROWTH_FACTOR,
    highlightId
  };
}

export function changeToggledGrowthFactor(toggledId) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_TOGGLED_GROWTH_FACTOR,
    toggledId
  };
}

export function changeCellLineColorBy(cellLineColorBy) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_CELL_LINE_COLOR_BY,
    cellLineColorBy
  };
}

export function changeCellLineSortBy(cellLineSortBy) {
  return {
    type: DATASET_GROWTH_FACTOR_PAKT_PERK_CHANGE_CELL_LINE_SORT_BY,
    cellLineSortBy
  };
}
